// This is a code snippet generated by example
// It sorts an array of integers in ascending order using Array.Sort method
int[] arr = {5, 3, 7, 1, 9}; // This is the array to be sorted
Array.Sort(arr); // This method sorts the array in place
Console.WriteLine("The sorted array is: ");
foreach (int num in arr) // This loop prints the array elements
{
    Console.Write(num + " ");
}
// The output is: 1 3 5 7 9
